title: Mohammad Massri # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Tripoli, Lebanon
  <br><br>
  Worked alongside python and mobile/desktop development.
  <br><br>

  Skills :

  <br>● Python
  <br>● C/C++
  <br>● SQL
  <br>● APIs
  <br>● AWS (Redshift)
  <br>● Git
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
