title: "<h5 style='color: #4287f5;'>Mohammad sup Massri</h5>" # your name (or website title) here
logo: "<div style='width:100px; height: 100px'>/images/logo.png?raw=true</div>" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Worked alongside Python and Web/Mobile development.
  <br><br>
  Tripoli, Lebanon
  <br><br>

  Skills :

  <br>● Python
  <br>● Django - DRF
  <br>● REST API
  <br>● Node.js
  <br>● AWS
  <br>● Linux
  <br>● Git
  <br>● Docker
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
